---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/29/2022 9:01 PM
---

WARM_ROCKET_EFFECT_ID = 'fw-warm'
COOL_ROCKET_EFFECT_ID = 'fw-cool'
COLORFUL_ROCKET_EFFECT_ID = 'fw-mix'
RANDOM_ROCKET_EFFECT_ID = 'fw-rdm'