---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/29/2022 9:01 PM
---

WARM_ROCKET_EFFECT_ID = 'fw-wrm'
COOL_ROCKET_EFFECT_ID = 'fw-col'
COLORFUL_ROCKET_EFFECT_ID = 'fw-mix'
RANDOM_ROCKET_EFFECT_ID = 'fw-rdm'
REGULAR_ROCKET_EFFECT_ID = 'fw-rrf'
SMALL_ROCKET_EFFECT_ID = 'fw-sml'
LARGE_ROCKET_EFFECT_ID = 'fw-lrg'
FLARE_ROCKET_EFFECT_ID = 'fw-flr'