---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/29/2022 7:51 PM
---
handler = require("event_handler")

handler.add_lib(require("scripts/rockets_handling"))

handler.add_lib(require("scripts/mortar_crate"))

local DebugRemoteApi = require('scripts/debug_api')
remote.add_interface("firework_debug", DebugRemoteApi)