---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/29/2022 7:51 PM
---
data:extend({
    {
        type = "item-subgroup",
        name = "firework-rockets",
        group = "combat",
        order = "firework-rockets"
    },
})

require 'prototypes/firework'
require 'prototypes/projectile_trails'
require 'prototypes/projectile_rockets'
require 'prototypes/mortar_crate'
require 'prototypes/items'
require 'prototypes/recipes'
require 'prototypes/technology'