---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/29/2022 7:51 PM
---
require 'constant'
-- Add script to regular rockets

if settings.startup['firework-rocket-add-firework-regular-rocket'].value then
    table.insert(data.raw['projectile']['explosive-rocket']['action']['action_delivery']['target_effects'], {
        type='script',
        effect_id=REGULAR_ROCKET_EFFECT_ID
    })
    table.insert(data.raw['projectile']['rocket']['action']['action_delivery']['target_effects'], {
        type='script',
        effect_id=REGULAR_ROCKET_EFFECT_ID
    })
end

if settings.startup['firework-rocket-fire-hazard'].value then
    local target_probability = settings.startup['firework-rocket-fire-hazard-chance'].value / 100
    for key, explosion in pairs(data.raw['explosion']) do
        if string.find(key, "firework-") then
            explosion['created_effect'] = {
                {
                    type = "direct",
                    probability = target_probability,
                    action_delivery =
                    {
                        type = "instant",
                        target_effects =
                        {
                            {
                                type = "create-fire",
                                entity_name = "fire-flame",
                                initial_ground_flame_count = 40,
                                offset_deviation = {{-5,-5}, {5, 5}}
                            }
                        },
                    }
                }
            }
        end
    end
end