---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/31/2022 5:59 PM
---

data:extend {
    --- Startup Tab
    {
        type = "int-setting",
        name = "firework-rocket-mortar-process-interval",
        description = "firework-rocket-mortar-process-interval",
        setting_type = "startup",
        default_value = 51,
        allowed_values = {19, 31, 41, 51, 61, 97, 113},
        order = "firework-100"
    },
    --- Global Tab
    {
        type = "string-setting",
        name = "firework-rocket-travel-range",
        description = "firework-rocket-travel-range",
        setting_type = "runtime-global",
        default_value = '16-48',
        allowed_values = {'8-40','10-42','16-48','32-64','48-80','60-90','72-104'},
        order = "firework-100"
    },
}