---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 9/4/2022 9:22 PM
---

data:extend({
    {
        type = "build-entity-achievement",
        name = "firework_rockets/party_automation",
        to_build = 'firework/mortar-crate',
        amount = 50,
        icon = "__firework_rockets__/graphics/achievement/icon.png",
        icon_size = 128,
        limited_to_one_game = true,
        order = 'z[firework]-01-party-automation'
    },
    {
        type = "produce-achievement",
        name = "firework_rockets/party_starter",
        item_product = 'firework/random-rocket',
        amount = 1000,
        icon = "__firework_rockets__/graphics/achievement/icon.png",
        icon_size = 128,
        limited_to_one_game = true,
        order = 'z[firework]-02-party-starter'
    },
    {
        type = "produce-achievement",
        name = "firework_rockets/eternal_party",
        item_product = 'firework/random-rocket',
        amount = 1000000,
        icon = "__firework_rockets__/graphics/achievement/icon.png",
        icon_size = 128,
        limited_to_one_game = true,
        order = 'z[firework]-03-eternal-party'
    }
})