---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 9/4/2022 9:22 PM
---

data:extend({
    {
        type = "build-entity-achievement",
        name = "firework_rockets-party_automation",
        to_build = 'firework-mortar_crate',
        amount = 20,
        icon = "__firework_rockets_assets__/graphics/achievement/icon.png",
        icon_size = 128,
        allow_without_fight = true,
        order = 'z[firework]-01-party-automation'
    },
    {
        type = "shoot-achievement",
        name = "firework_rockets-party_starter",
        ammo_type = 'firework-random_rocket',
        amount = 100,
        icon = "__firework_rockets_assets__/graphics/achievement/icon.png",
        icon_size = 128,
        allow_without_fight = true,
        order = 'z[firework]-02-party-starter'
    },
    {
        type = "produce-achievement",
        name = "firework_rockets-eternal_party",
        item_product = 'firework-random_rocket',
        amount = 1000000,
        icon = "__firework_rockets_assets__/graphics/achievement/icon.png",
        icon_size = 128,
        limited_to_one_game = false,
        order = 'z[firework]-03-eternal-party'
    }
})