---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/29/2022 7:56 PM
---

local SharedFunctions = require 'prototypes.shared'

local sound_type = {
    ['large'] = {
        {
            filename = '__firework_rockets__/sound/large_explosion1.ogg',
            volume = 0.7
        },
        {
            filename = '__firework_rockets__/sound/large_explosion2.ogg',
            volume = 0.7
        },
        {
            filename = '__firework_rockets__/sound/large_explosion3.ogg',
            volume = 0.7
        },
        {
            filename = '__firework_rockets__/sound/large_explosion4.ogg',
            volume = 0.7
        }
    },
    ['regular'] = {
        {
            filename = '__firework_rockets__/sound/explosion1.ogg',
            volume = 0.7
        },
        {
            filename = '__firework_rockets__/sound/explosion2.ogg',
            volume = 0.7
        },
        {
            filename = '__firework_rockets__/sound/explosion3.ogg',
            volume = 0.7
        },
        {
            filename = '__firework_rockets__/sound/explosion4.ogg',
            volume = 0.7
        },
        {
            filename = '__firework_rockets__/sound/explosion5.ogg',
            volume = 0.7
        },
    },
    ['flare'] = {
        {
            filename = '__firework_rockets__/sound/explosion_fizz_1.ogg',
            volume = 0.7
        },
        {
            filename = '__firework_rockets__/sound/explosion_fizz_2.ogg',
            volume = 0.7
        }
    }
}

local get_sound_pack = function(type)
    return sound_type[type]
end

local build_firework = function(data)
    data['scale'] = data['scale'] or 1
    local filename = "__firework_rockets__/graphics/firework_"..data['version'].."/"..data['type']..".png"
    local explosion = {
        type = "explosion",
        name = "firework-"..data['version'].."-"..data['type'].."-"..SharedFunctions.convert_scale(data['scale']),
        subgroup = 'explosions',
        order = "firework-"..data['version'].."-"..data['type'].."-"..SharedFunctions.convert_scale(data['scale']),
        render_layer = "explosion",
        flags = { "not-on-map" },
        light_intensity_peak_end_progress = 0.0,
        light_size_peak_end_progress = 0.3,
        animations = {
            {
                filename = filename,
                width = data['width'],
                height = data['height'],
                line_length = data['line_length'],
                frame_count = data['frame_count'],
                animation_speed = data['animation_speed'],
                scale = data['scale']
            }
        },
        sound = {
            variations = get_sound_pack(data['sound_type']),
            audible_distance_modifier = 1.5,
        },
    }
    explosion = SharedFunctions.process_glow(explosion, data, 1)
    explosion = SharedFunctions.process_lighting(explosion, data)
    return explosion
end

local firework_1_data = {
 {
    version = 1,
    type = "green",
    width = 378,
    height = 513,
    line_length = 9,
    frame_count = 42,
    animation_speed = 0.5,
    draw_as_glow = true,
    scale = 1,
    lighting_intensity = 1,
    lighting_color = SharedFunctions.get_color('green'),
    lighting_size = 10,
    lighting_shift = {-0.5, -2},
    sound_type = 'regular',
 },
 {
     version = 1,
     type = "orange",
     width = 402,
     height = 572,
     line_length = 8,
     frame_count = 42,
     animation_speed = 0.5,
     draw_as_glow = true,
     scale = 1,
     lighting_intensity = 1,
     lighting_color = SharedFunctions.get_color('orange'),
     lighting_size = 10,
     lighting_shift = {-0.5, -2},
     sound_type = 'regular',
 },
 {
     version = 1,
     type = "purple",
     width = 437,
     height = 581,
     line_length = 8,
     frame_count = 42,
     animation_speed = 0.5,
     draw_as_glow = true,
     scale = 1,
     lighting_intensity = 1,
     lighting_color = SharedFunctions.get_color('purple'),
     lighting_size = 10,
     lighting_shift = {-0.5, -2},
     sound_type = 'regular',
 },
}

for _, firework_object in pairs(firework_1_data) do
    data:extend({ build_firework(firework_object) })
end

local firework_2_data = {
    {
        version = 2,
        type = "orange",
        width = 269,
        height = 448,
        line_length = 13,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('orange'),
        lighting_size = 10,
        lighting_shift = {-0.5, -1},
        sound_type = 'regular',
    },
    {
        version = 2,
        type = "purple",
        width = 306,
        height = 449,
        line_length = 8,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('purple'),
        lighting_size = 10,
        lighting_shift = {-0.5, -1},
        sound_type = 'regular',
    },
    {
        version = 2,
        type = "blue",
        width = 424,
        height = 367,
        line_length = 8,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('blue'),
        lighting_size = 10,
        lighting_shift = {-0.5, -2},
        sound_type = 'regular',
    },
}

for _, firework_object in pairs(firework_2_data) do
    data:extend({ build_firework(firework_object) })
end

local firework_3_data = {
    {
        version = 3,
        type = "green",
        width = 318,
        height = 331,
        line_length = 11,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('green'),
        lighting_size = 10,
        lighting_shift = {-0.5, -1},
        sound_type = 'regular',
    },
    {
        version = 3,
        type = "pink",
        width = 315,
        height = 362,
        line_length = 11,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('pink'),
        lighting_size = 10,
        lighting_shift = {0, -1},
        sound_type = 'regular',
    },
    {
        version = 3,
        type = "red",
        width = 284,
        height = 369,
        line_length = 12,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('red'),
        lighting_size = 10,
        lighting_shift = {0, -1},
        sound_type = 'regular',
    }
}

for _, firework_object in pairs(firework_3_data) do
    data:extend({ build_firework(firework_object) })
end

local firework_4_data = {
    {
        version = 4,
        type = "v1",
        width = 469,
        height = 468,
        line_length = 7,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 0.75,
        lighting_color = SharedFunctions.get_color('white'),
        lighting_size =10,
        lighting_shift = {-0.5, -1},
        sound_type = 'regular',
    },
    {
        version = 4,
        type = "v2",
        width = 545,
        height = 532,
        line_length = 7,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 0.75,
        lighting_color = SharedFunctions.get_color('white'),
        lighting_size = 10,
        lighting_shift = {0, -1},
        sound_type = 'regular',
    },
    {
        version = 4,
        type = "v3",
        width = 529,
        height = 482,
        line_length = 6,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 0.75,
        lighting_color = SharedFunctions.get_color('white'),
        lighting_size = 10,
        lighting_shift = {0, -1},
        sound_type = 'regular',
    }
}

for _, firework_object in pairs(firework_4_data) do
    data:extend({ build_firework(firework_object) })
end

local firework_5_data = {
    {
        version = 5,
        type = "pink",
        width = 335,
        height = 336,
        line_length = 9,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1.5,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('yellow'),
        lighting_size = 15,
        lighting_shift = {-0.5, -1},
        sound_type = 'large',
    },
    {
        version = 5,
        type = "purple",
        width = 329,
        height = 332,
        line_length = 9,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1.5,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('purple'),
        lighting_size = 15,
        lighting_shift = {0, -1},
        sound_type = 'large',
    },
    {
        version = 5,
        type = "yellow",
        width = 335,
        height = 338,
        line_length = 9,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1.5,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('pink'),
        lighting_size = 15,
        lighting_shift = {0, -1},
        sound_type = 'large',
    }
}

for _, firework_object in pairs(firework_5_data) do
    data:extend({ build_firework(firework_object) })
end

local firework_6_data = {
    {
        version = 6,
        type = "yellow",
        width = 527,
        height = 503,
        line_length = 7,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('yellow'),
        lighting_size = 15,
        lighting_shift = {0, -1},
        sound_type = 'large',
    },
    {
        version = 6,
        type = "white",
        width = 453,
        height = 445,
        line_length = 7,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('white'),
        lighting_size = 15,
        lighting_shift = {0, -1},
        sound_type = 'large',
    },
    {
        version = 6,
        type = "red",
        width = 459,
        height = 479,
        line_length = 7,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('red'),
        lighting_size = 15,
        lighting_shift = {0, -1},
        sound_type = 'large',
    }
}

for _, firework_object in pairs(firework_6_data) do
    data:extend({ build_firework(firework_object) })
end

local firework_7_data = {
    {
        version = 7,
        type = "red",
        width = 491,
        height = 513,
        line_length = 8,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('red'),
        lighting_size = 15,
        lighting_shift = {0, -1},
        sound_type = 'large',
    },
    {
        version = 7,
        type = "white",
        width = 441,
        height = 517,
        line_length = 9,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('white'),
        lighting_size = 15,
        lighting_shift = {0, -1},
        sound_type = 'large',
    },
    {
        version = 7,
        type = "yellow",
        width = 528,
        height = 508,
        line_length = 7,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('yellow'),
        lighting_size = 15,
        lighting_shift = {0, -1},
        sound_type = 'large',
    },
}

for _, firework_object in pairs(firework_7_data) do
    data:extend({ build_firework(firework_object) })
end

local firework_8_data = {
    {
        version = 8,
        type = "yellow",
        width = 329,
        height = 539,
        line_length = 9,
        frame_count = 42,
        animation_speed = 0.45,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('yellow'),
        lighting_size = 10,
        lighting_shift = {0, -1},
        sound_type = 'flare',
    },
    {
        version = 8,
        type = "orange",
        width = 337,
        height = 501,
        line_length = 9,
        frame_count = 42,
        animation_speed = 0.45,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('orange'),
        lighting_size = 10,
        lighting_shift = {0, -1},
        sound_type = 'flare',
    },
    {
        version = 8,
        type = "purple",
        width = 343,
        height = 502,
        line_length = 8,
        frame_count = 42,
        animation_speed = 0.45,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('purple'),
        lighting_size = 10,
        lighting_shift = {0, -1},
        sound_type = 'flare',
    },
}

for _, firework_object in pairs(firework_8_data) do
    data:extend({ build_firework(firework_object) })
end

local firework_9_data = {
    {
        version = 9,
        type = "v1",
        width = 375,
        height = 395,
        line_length = 8,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 0.75,
        lighting_color = SharedFunctions.get_color('white'),
        lighting_size = 10,
        lighting_shift = {0, -1},
        sound_type = 'regular',
    },
    {
        version = 9,
        type = "v2",
        width = 370,
        height = 396,
        line_length = 8,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 0.75,
        lighting_color = SharedFunctions.get_color('white'),
        lighting_size = 10,
        lighting_shift = {0, -1},
        sound_type = 'regular',
    },
    {
        version = 9,
        type = "v3",
        width = 403,
        height = 403,
        line_length = 7,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 0.75,
        lighting_color = SharedFunctions.get_color('white'),
        lighting_size = 10,
        lighting_shift = {0, -1},
        sound_type = 'regular',
    },
}

for _, firework_object in pairs(firework_9_data) do
    data:extend({ build_firework(firework_object) })
end

local firework_10_data = {
    {
        version = 10,
        type = "yellow",
        width = 494,
        height = 548,
        line_length = 8,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('yellow'),
        lighting_size = 15,
        lighting_shift = {0, -1},
        sound_type = 'large',
    },
    {
        version = 10,
        type = "pink",
        width = 524,
        height = 522,
        line_length = 7,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('pink'),
        lighting_size = 15,
        lighting_shift = {0, -1},
        sound_type = 'large',
    },
    {
        version = 10,
        type = "blue",
        width = 529,
        height = 531,
        line_length = 7,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('blue'),
        lighting_size = 15,
        lighting_shift = {0, -1},
        sound_type = 'large',
    },
}

for _, firework_object in pairs(firework_10_data) do
    data:extend({ build_firework(firework_object) })
end