---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/29/2022 7:56 PM
---

local SharedFunctions = require 'prototypes.shared'

local build_firework = function(data)
    data['scale'] = data['scale'] or 1
    local filename = "__firework_rockets__/graphics/firework_"..data['version'].."/"..data['type']..".png"
    local explosion = {
        type = "explosion",
        name = "firework-"..data['version'].."-"..data['type'].."-"..SharedFunctions.convert_scale(data['scale']),
        subgroup = 'explosions',
        order = "firework-"..data['version'].."-"..data['type'].."-"..SharedFunctions.convert_scale(data['scale']),
        render_layer = "explosion",
        flags = { "not-on-map" },
        light_intensity_peak_end_progress = 0.0,
        light_size_peak_end_progress = 0.3,
        animations = {
            {
                filename = filename,
                width = data['width'],
                height = data['height'],
                line_length = data['line_length'],
                frame_count = data['frame_count'],
                animation_speed = data['animation_speed'],
                scale = data['scale']
            }
        },
        sound = {
            variations = {
                {
                    filename = '__firework_rockets__/sound/explosion2.ogg',
                    volume = 0.7
                },
                {
                    filename = '__firework_rockets__/sound/explosion3.ogg',
                    volume = 0.7
                }
            },
            audible_distance_modifier = 1.5,
        },
    }
    explosion = SharedFunctions.process_glow(explosion, data, 1)
    explosion = SharedFunctions.process_lighting(explosion, data)
    return explosion
end

local firework_1_data = {
 {
    version = 1,
    type = "green",
    width = 378,
    height = 513,
    line_length = 9,
    frame_count = 42,
    animation_speed = 0.5,
    draw_as_glow = true,
    scale = 1,
    lighting_intensity = 1,
    lighting_color = SharedFunctions.get_color('green'),
    lighting_size = 10,
    lighting_shift = {-0.5, -2}
 },
 {
     version = 1,
     type = "orange",
     width = 402,
     height = 572,
     line_length = 8,
     frame_count = 42,
     animation_speed = 0.5,
     draw_as_glow = true,
     scale = 1,
     lighting_intensity = 1,
     lighting_color = SharedFunctions.get_color('orange'),
     lighting_size = 10,
     lighting_shift = {-0.5, -2}
 },
 {
     version = 1,
     type = "purple",
     width = 437,
     height = 581,
     line_length = 8,
     frame_count = 42,
     animation_speed = 0.5,
     draw_as_glow = true,
     scale = 1,
     lighting_intensity = 1,
     lighting_color = SharedFunctions.get_color('purple'),
     lighting_size = 10,
     lighting_shift = {-0.5, -2}
 },
}

for _, firework_object in pairs(firework_1_data) do
    data:extend({ build_firework(firework_object) })
end

local firework_2_data = {
    {
        version = 2,
        type = "orange",
        width = 269,
        height = 448,
        line_length = 13,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('orange'),
        lighting_size = 10,
        lighting_shift = {-0.5, -1}
    },
    {
        version = 2,
        type = "purple",
        width = 306,
        height = 449,
        line_length = 8,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('purple'),
        lighting_size = 10,
        lighting_shift = {-0.5, -1}
    },
    {
        version = 2,
        type = "blue",
        width = 424,
        height = 367,
        line_length = 8,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('blue'),
        lighting_size = 10,
        lighting_shift = {-0.5, -2}
    },
}

for _, firework_object in pairs(firework_2_data) do
    data:extend({ build_firework(firework_object) })
end

local firework_3_data = {
    {
        version = 3,
        type = "green",
        width = 318,
        height = 331,
        line_length = 11,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('green'),
        lighting_size = 10,
        lighting_shift = {-0.5, -1}
    },
    {
        version = 3,
        type = "pink",
        width = 315,
        height = 362,
        line_length = 11,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('pink'),
        lighting_size = 10,
        lighting_shift = {0, -1},
    },
    {
        version = 3,
        type = "red",
        width = 284,
        height = 369,
        line_length = 12,
        frame_count = 42,
        animation_speed = 0.5,
        draw_as_glow = true,
        scale = 1,
        lighting_intensity = 1,
        lighting_color = SharedFunctions.get_color('red'),
        lighting_size = 10,
        lighting_shift = {0, -1}
    }
}

for _, firework_object in pairs(firework_3_data) do
    data:extend({ build_firework(firework_object) })
end