---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/29/2022 8:38 PM
---

require '__firework_rockets__/constant'

---
---
--- 4 Types of rocket,
--- random (ALL types, ALL color),
--- colorful (all colors types),
--- warm (pink, orange, yellow),
--- cool (blue, green, purple)
---

data:extend({
    {
        type = "projectile",
        name = "firework-random_rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = RANDOM_ROCKET_EFFECT_ID,
                    }
                }
            }
        },
        animation = require("__base__.prototypes.entity.rocket-projectile-pictures").animation({1, 0.8, 0.3}),
        shadow = require("__base__.prototypes.entity.rocket-projectile-pictures").shadow,
        smoke = require("__base__.prototypes.entity.rocket-projectile-pictures").smoke,
    },
    {
        type = "projectile",
        name = "firework-colorful_rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = COLORFUL_ROCKET_EFFECT_ID,

                    }
                }
            }
        },
        animation = require("__base__.prototypes.entity.rocket-projectile-pictures").animation({1, 0.8, 0.3}),
        shadow = require("__base__.prototypes.entity.rocket-projectile-pictures").shadow,
        smoke = require("__base__.prototypes.entity.rocket-projectile-pictures").smoke,
    },
    {
        type = "projectile",
        name = "firework-warm_rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = WARM_ROCKET_EFFECT_ID,

                    }
                }
            }
        },
        animation = require("__base__.prototypes.entity.rocket-projectile-pictures").animation({1, 0.8, 0.3}),
        shadow = require("__base__.prototypes.entity.rocket-projectile-pictures").shadow,
        smoke = require("__base__.prototypes.entity.rocket-projectile-pictures").smoke,
    },
    {
        type = "projectile",
        name = "firework-cool_rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = COOL_ROCKET_EFFECT_ID,

                    }
                }
            }
        },
        animation = require("__base__.prototypes.entity.rocket-projectile-pictures").animation({1, 0.8, 0.3}),
        shadow = require("__base__.prototypes.entity.rocket-projectile-pictures").shadow,
        smoke = require("__base__.prototypes.entity.rocket-projectile-pictures").smoke,
    },
    {
        type = "projectile",
        name = "firework-small_rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = SMALL_ROCKET_EFFECT_ID,

                    }
                }
            }
        },
        animation = require("__base__.prototypes.entity.rocket-projectile-pictures").animation({1, 0.8, 0.3}),
        shadow = require("__base__.prototypes.entity.rocket-projectile-pictures").shadow,
        smoke = require("__base__.prototypes.entity.rocket-projectile-pictures").smoke,
    },
    {
        type = "projectile",
        name = "firework-large_rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = LARGE_ROCKET_EFFECT_ID,

                    }
                }
            }
        },
        animation = require("__base__.prototypes.entity.rocket-projectile-pictures").animation({1, 0.8, 0.3}),
        shadow = require("__base__.prototypes.entity.rocket-projectile-pictures").shadow,
        smoke = require("__base__.prototypes.entity.rocket-projectile-pictures").smoke,
    },
    {
        type = "projectile",
        name = "firework-flare_rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = FLARE_ROCKET_EFFECT_ID,

                    }
                }
            }
        },
        animation = require("__base__.prototypes.entity.rocket-projectile-pictures").animation({1, 0.8, 0.3}),
        shadow = require("__base__.prototypes.entity.rocket-projectile-pictures").shadow,
        smoke = require("__base__.prototypes.entity.rocket-projectile-pictures").smoke,
    },
})