---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/29/2022 8:38 PM
---

require '__firework_rockets__/constant'

---
---
--- 4 Types of rocket,
--- random (ALL types, ALL color),
--- colorful (all colors types),
--- warm (pink, orange, yellow),
--- cool (blue, green, purple)
---

data:extend({
    {
        type = "projectile",
        name = "firework/random-rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = RANDOM_ROCKET_EFFECT_ID,
                    }
                }
            }
        },
        animation =
        {
            filename = "__base__/graphics/entity/rocket/rocket.png",
            draw_as_glow = true,
            frame_count = 8,
            line_length = 8,
            width = 9,
            height = 35,
            shift = {0, 0},
            priority = "high"
        }
    },
    {
        type = "projectile",
        name = "firework/colorful-rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = COLORFUL_ROCKET_EFFECT_ID,

                    }
                }
            }
        },
        animation =
        {
            filename = "__base__/graphics/entity/rocket/rocket.png",
            draw_as_glow = true,
            frame_count = 8,
            line_length = 8,
            width = 9,
            height = 35,
            shift = {0, 0},
            priority = "high"
        }
    },
    {
        type = "projectile",
        name = "firework/warm-rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = WARM_ROCKET_EFFECT_ID,

                    }
                }
            }
        },
        animation =
        {
            filename = "__base__/graphics/entity/rocket/rocket.png",
            draw_as_glow = true,
            frame_count = 8,
            line_length = 8,
            width = 9,
            height = 35,
            shift = {0, 0},
            priority = "high"
        }
    },
    {
        type = "projectile",
        name = "firework/cool-rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = COOL_ROCKET_EFFECT_ID,

                    }
                }
            }
        },
        animation =
        {
            filename = "__base__/graphics/entity/rocket/rocket.png",
            draw_as_glow = true,
            frame_count = 8,
            line_length = 8,
            width = 9,
            height = 35,
            shift = {0, 0},
            priority = "high"
        }
    },
    {
        type = "projectile",
        name = "firework/small-rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = SMALL_ROCKET_EFFECT_ID,

                    }
                }
            }
        },
        animation =
        {
            filename = "__base__/graphics/entity/rocket/rocket.png",
            draw_as_glow = true,
            frame_count = 8,
            line_length = 8,
            width = 9,
            height = 35,
            shift = {0, 0},
            priority = "high"
        }
    },
    {
        type = "projectile",
        name = "firework/large-rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = LARGE_ROCKET_EFFECT_ID,

                    }
                }
            }
        },
        animation =
        {
            filename = "__base__/graphics/entity/rocket/rocket.png",
            draw_as_glow = true,
            frame_count = 8,
            line_length = 8,
            width = 9,
            height = 35,
            shift = {0, 0},
            priority = "high"
        }
    },
    {
        type = "projectile",
        name = "firework/flare-rocket",
        flags = {"not-on-map"},
        acceleration = 0.005,
        turn_speed = 0,
        turning_speed_increases_exponentially_with_projectile_speed = false,
        direction_only = true,
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "script",
                        effect_id = FLARE_ROCKET_EFFECT_ID,

                    }
                }
            }
        },
        animation =
        {
            filename = "__base__/graphics/entity/rocket/rocket.png",
            draw_as_glow = true,
            frame_count = 8,
            line_length = 8,
            width = 9,
            height = 35,
            shift = {0, 0},
            priority = "high"
        }
    },
})