---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/30/2022 5:42 PM
---

data:extend({
    {
        type = "recipe",
        name = 'firework-warm_rocket',
        enabled = false,
        energy_required = 5,
        ingredients =
        {
            {type="item", name="rocket", amount=10},
        },
        results = {
            {type="item", name="firework-warm_rocket", amount=20},
        },
        allow_quality = false,
        auto_recycle = false,
        order="firework-01"
    },
    {
        type = "recipe",
        name = 'firework-cool_rocket',
        enabled = false,
        energy_required = 5,
        allow_quality = false,
        auto_recycle = false,
        ingredients =
        {
            {type="item", name="rocket", amount=10},
        },
        results = {
            {type="item", name="firework-cool_rocket", amount=20},
        },
        order="firework-02"
    },
    {
        type = "recipe",
        name = 'firework-colorful_rocket',
        enabled = false,
        energy_required = 5,
        allow_quality = false,
        auto_recycle = false,
        ingredients =
        {
            {type="item", name="firework-warm_rocket", amount=5},
            {type="item", name="firework-cool_rocket", amount=5},
        },
        results = {
            {type="item", name="firework-colorful_rocket", amount=10},
        },
        order="firework-03"
    },
    {
        type = "recipe",
        name = 'firework-random_rocket',
        enabled = false,
        energy_required = 10,
        allow_quality = false,
        auto_recycle = false,
        ingredients =
        {
            {type="item", name="firework-warm_rocket", amount=5},
            {type="item", name="firework-cool_rocket", amount=5},
            {type="item", name="firework-colorful_rocket", amount=5},
            {type="item", name="decider-combinator", amount=5},
        },
        results = {
            {type="item", name="firework-random_rocket", amount=10},
        },
        order="firework-04"
    },
    {
        type = "recipe",
        name = 'firework-small_rocket',
        enabled = false,
        energy_required = 5,
        allow_quality = false,
        auto_recycle = false,
        ingredients =
        {
            {type="item", name="firework-warm_rocket", amount=5},
            {type="item", name="firework-cool_rocket", amount=5},
        },
        results = {
            {type="item", name="firework-small_rocket", amount=10},
        },
        order="firework-05"
    },
    {
        type = "recipe",
        name = 'firework-large_rocket',
        enabled = false,
        energy_required = 5,
        allow_quality = false,
        auto_recycle = false,
        ingredients =
        {
            {type="item", name="firework-warm_rocket", amount=5},
            {type="item", name="firework-cool_rocket", amount=5},
        },
        results = {
            {type="item", name="firework-large_rocket", amount=10},
        },
        order="firework-06"
    },
    {
        type = "recipe",
        name = 'firework-flare_rocket',
        enabled = false,
        energy_required = 5,
        allow_quality = false,
        auto_recycle = false,
        ingredients =
        {
            {type="item", name="firework-warm_rocket", amount=5},
            {type="item", name="firework-cool_rocket", amount=5},
        },
        results = {
            {type="item", name="firework-flare_rocket", amount=10},
        },
        order="firework-07"
    },
    {
        type = "recipe",
        name = 'firework-mortar_crate',
        enabled = false,
        energy_required = 5,
        allow_quality = false,
        auto_recycle = false,
        ingredients =
        {
            {type="item", name="iron-plate", amount=20},
            {type="item", name="steel-plate", amount=10},
            {type="item", name="copper-plate", amount=20}
        },
        results = {
            {type="item", name="firework-mortar_crate", amount=1},
        },
        order="firework-10"
    },
})