---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/29/2022 8:00 PM
---

local SharedFunctions = {}

function SharedFunctions.process_glow(entity, data, layer)
    if data['draw_as_glow'] then
        entity['animations'][layer]['draw_as_glow'] = true
    end
    return entity
end

function SharedFunctions.process_lighting(entity, data)
    if data['lighting_color'] and data['lighting_intensity'] and data['lighting_size'] then
        entity['light'] = {
            intensity = data['lighting_intensity'],
            color = data['lighting_color'],
            size = data['lighting_size']
        }

        if data['lighting_shift'] then
            entity['light']['shift'] = data['lighting_shift']
        end
    end
    return entity
end

function SharedFunctions.convert_scale(scale)
    return string.gsub(tostring(scale),"%.", "-")
end

local colors = {
    ['green'] = { r = 0.173, g = 0.824, b = 0.250 },
    ['blue'] = { r = 0.343, g = 0.683, b = 1.000 },
    ['orange'] =  { r = 1.000, g = 0.630, b = 0.259 },
    ['purple'] = { r = 0.821, g = 0.440, b = 0.998 },
    ['pink'] = { r = 1.000, g = 0.520, b = 0.633 },
    ['red'] = { r = 1.000, g = 0.166, b = 0.141 }
}
function SharedFunctions.get_color(name)
    if colors[name] then
        return colors[name]
    end
    return {r=1, g=1, b=1}
end

return SharedFunctions