---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/30/2022 5:30 PM
---

data:extend({
    {
        type = "technology",
        name = 'firework-techs',
        icon_size = 64,
        icon = "__firework_rockets_assets__/graphics/icons/firework_tech.png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = "firework-random_rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework-colorful_rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework-cool_rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework-warm_rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework-large_rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework-small_rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework-flare_rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework-mortar_crate"
            }
        },
        prerequisites = {"rocketry"},
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"military-science-pack", 1},
                {"chemical-science-pack", 1},
            },
            time = 30,
            count = 100
        },
    },
})