---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/30/2022 5:30 PM
---

data:extend({
    {
        type = "technology",
        name = 'firework/techs',
        icon_size = 64,
        icon = "__firework_rockets__/graphics/icons/firework_tech.png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = "firework/random-rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework/colorful-rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework/cool-rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework/warm-rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework/large-rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework/small-rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework/flare-rocket"
            },
            {
                type = "unlock-recipe",
                recipe = "firework/mortar-crate"
            }
        },
        prerequisites = {"rocketry"},
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"military-science-pack", 1},
                {"chemical-science-pack", 1},
            },
            time = 30,
            count = 100
        },
    },
})