---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 9/7/2022 11:31 PM
---
local motar_crate = require('scripts/mortar_crate')

local DebugAPI = {}

function DebugAPI.print_mortar_details()
    motar_crate.get_debug_data()
end

function DebugAPI.list_inactive_motars()
    motar_crate.debug_list_inactive_motars()
end

return DebugAPI