---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/30/2022 11:07 PM
---

local ScriptSharedFunctions = require 'shared'

local weapon_trigger_effects = function(event)
    if ScriptSharedFunctions.pick_firework(event.effect_id)
    then
        ScriptSharedFunctions.create_firework(
            event.surface_index,
            event.target_position,
            event.effect_id
        )
    end
end

local update_storages = function()
    storage.min_travel_distance, storage.max_travel_distance =
        string.match(settings.global['firework-rocket-travel-range'].value, "(%d+)%-(%d+)")
    storage.min_travel_distance = tonumber(storage.min_travel_distance)
    storage.max_travel_distance = tonumber(storage.max_travel_distance)
    storage.emit_pollution = game.map_settings.pollution.enabled and settings.global['firework-rocket-emit-pollution'].value
    storage.emit_pollution_value = settings.global['firework-rocket-emit-pollution-value'].value
end

local firework_handling = {}

firework_handling.events =
{
    [defines.events.on_script_trigger_effect] = weapon_trigger_effects,
    [defines.events.on_runtime_mod_setting_changed] = update_storages
}

firework_handling.on_init = function(event)
    update_storages()
end

firework_handling.on_configuration_changed = function(event)
    update_storages()
end

return firework_handling