---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/30/2022 11:07 PM
---

local ScriptSharedFunctions = require 'shared'

local weapon_trigger_effects = function(event)
    if ScriptSharedFunctions.pick_firework(event.effect_id)
    then
        ScriptSharedFunctions.create_firework(
            event.surface_index,
            event.target_position,
            event.effect_id
        )
    end
end

local update_globals = function()
    global.min_travel_distance, global.max_travel_distance =
        string.match(settings.global['firework-rocket-travel-range'].value, "(%d+)%-(%d+)")
    global.min_travel_distance = tonumber(global.min_travel_distance)
    global.max_travel_distance = tonumber(global.max_travel_distance)
end

local firework_handling = {}

firework_handling.events =
{
    [defines.events.on_script_trigger_effect] = weapon_trigger_effects,
    [defines.events.on_runtime_mod_setting_changed] = update_globals
}

firework_handling.on_init = function(event)
    update_globals()
end

firework_handling.on_configuration_changed = function(event)
    update_globals()
end

return firework_handling