---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/31/2022 12:45 AM
---
require 'constant'

---
--- firework-trail-firework-1-green-1
--- firework-trail-firework-1-orange-1
--- firework-trail-firework-1-purple-1
--- firework-trail-firework-2-orange-1
--- firework-trail-firework-2-purple-1
--- firework-trail-firework-2-blue-1
--- firework-trail-firework-3-green-1
--- firework-trail-firework-3-pink-1
--- firework-trail-firework-3-red-1
---

--- for full available list
--- @see prototypes/projectile_trails.lua
local warm_firework = {
    'firework-trail-firework-1-orange-1',
    'firework-trail-firework-2-orange-1',
    'firework-trail-firework-3-red-1',
    'firework-trail-firework-3-pink-1',
    'firework-trail-firework-5-pink-1-5',
    'firework-trail-firework-5-yellow-1-5',
    'firework-trail-firework-6-red-1',
    'firework-trail-firework-6-yellow-1',
}

local warm_firework_size = #warm_firework

local cool_firework = {
    'firework-trail-firework-5-purple-1-5',
    'firework-trail-firework-1-purple-1',
    'firework-trail-firework-1-green-1',
    'firework-trail-firework-2-blue-1',
    'firework-trail-firework-2-purple-1',
    'firework-trail-firework-3-green-1',
    'firework-trail-firework-6-white-1'
}
local cool_firework_size = #cool_firework

local colorful_firework = {
    'firework-trail-firework-4-v1-1',
    'firework-trail-firework-4-v2-1',
    'firework-trail-firework-4-v3-1',
}
local colorful_firework_size = #colorful_firework



local pick_firework = {
    [WARM_ROCKET_EFFECT_ID] = function(args)
        return warm_firework[math.random(1, warm_firework_size)]
    end,
    [COOL_ROCKET_EFFECT_ID] = function(args)
        return cool_firework[math.random(1, cool_firework_size)]
    end,
    [COLORFUL_ROCKET_EFFECT_ID] = function(args)
        return colorful_firework[math.random(1, colorful_firework_size)]
    end,
    [RANDOM_ROCKET_EFFECT_ID] = function(args)
        local type = math.random(1, 3)
        if type == 1 then
            return colorful_firework[math.random(1, colorful_firework_size)]
        elseif type == 2 then
            return warm_firework[math.random(1, warm_firework_size)]
        else
            return cool_firework[math.random(1, colorful_firework_size)]
        end
    end,
}

local SharedFunctions = {}

function SharedFunctions.pick_firework(effect_id)
    return pick_firework[effect_id]
end

function SharedFunctions.create_firework(surface_index, source_position, effect_id, target_position)
    local surface = game.surfaces[surface_index]
    if surface and surface.valid and source_position then
        local name  = pick_firework[effect_id]()
        if source_position then
            target_position = target_position or
                    {
                        x = source_position.x + math.random(-8,8),
                        y = source_position.y - math.random(16,32)
                    }
            surface.create_entity({
                name = name,
                position = source_position,
                target = target_position,
                speed = 0.1,
                max_range = math.random(global.min_travel_distance, global.max_travel_distance)
            })
        end
    end
end

return SharedFunctions